# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ta_joga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('apelido_pf_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Perfil_usuario')),
                ('nome_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Jogos')),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='nme_reg_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Registro_usuario'),
        ),
        migrations.AddField(
            model_name='participa',
            name='apelido_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Perfil_usuario'),
        ),
        migrations.AddField(
            model_name='participa',
            name='nme_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Times'),
        ),
    ]
