# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='nome',
            field=models.CharField(default='Nome', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='apelido',
            field=models.CharField(default='Apelido', max_length=20),
        ),
        migrations.AddField(
            model_name='registro_usuario',
            name='email',
            field=models.CharField(default='E-mail', max_length=200),
        ),
        migrations.AddField(
            model_name='times',
            name='nome',
            field=models.CharField(default='Nome', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro_usuario',
            name='nome',
            field=models.CharField(default='Nome', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro_usuario',
            name='senha',
            field=models.CharField(default='Senha', max_length=10),
        ),
    ]
