# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0002_auto_20170511_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='nme_reg_usr',
        ),
        migrations.AddField(
            model_name='registro_usuario',
            name='apelido',
            field=models.CharField(default='Nickname', max_length=20),
        ),
        migrations.AddField(
            model_name='registro_usuario',
            name='dta_nasc',
            field=models.CharField(default='Date', max_length=10),
        ),
        migrations.AddField(
            model_name='registro_usuario',
            name='extras',
            field=models.TextField(default='Extras'),
        ),
        migrations.AddField(
            model_name='registro_usuario',
            name='nicks',
            field=models.TextField(default='Nicknames'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='apelido_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Registro_usuario'),
        ),
        migrations.AlterField(
            model_name='registro_usuario',
            name='nome',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro_usuario',
            name='senha',
            field=models.CharField(default='Password', max_length=10),
        ),
        migrations.AlterField(
            model_name='ta_joga',
            name='apelido_pf_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Registro_usuario'),
        ),
        migrations.DeleteModel(
            name='Perfil_usuario',
        ),
    ]
