# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0003_auto_20170514_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/dist/img/'),
            preserve_default=False,
        ),
    ]
