# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 08:08
from __future__ import unicode_literals

import PartyAssembler.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0004_jogos_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50)),
                ('game_cover', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=PartyAssembler.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(default='Nome', max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('party_img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=PartyAssembler.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ta_Game_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('level', models.IntegerField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('nickname', models.CharField(default='Nickname', max_length=20, primary_key=True, serialize=False)),
                ('tags', models.TextField(default='Tags')),
                ('description', models.TextField(default='Description')),
                ('profile_img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=PartyAssembler.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='participa',
            name='apelido_usr',
        ),
        migrations.RemoveField(
            model_name='participa',
            name='nme_time',
        ),
        migrations.RemoveField(
            model_name='ta_joga',
            name='apelido_pf_usr',
        ),
        migrations.RemoveField(
            model_name='ta_joga',
            name='nome_jogo',
        ),
        migrations.DeleteModel(
            name='Jogos',
        ),
        migrations.DeleteModel(
            name='Participa',
        ),
        migrations.DeleteModel(
            name='Registro_usuario',
        ),
        migrations.DeleteModel(
            name='ta_joga',
        ),
        migrations.DeleteModel(
            name='Times',
        ),
        migrations.AddField(
            model_name='ta_game_user',
            name='user_nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.User_profile'),
        ),
        migrations.AddField(
            model_name='participate',
            name='party_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Party'),
        ),
        migrations.AddField(
            model_name='participate',
            name='usr_nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.User_profile'),
        ),
        migrations.AddField(
            model_name='create',
            name='party_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Party'),
        ),
        migrations.AddField(
            model_name='create',
            name='usr_nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.User_profile'),
        ),
    ]
